[tool.ruff]
line-length = 120
ignore = ["D100"]
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "D",  # pydocstyle
    "I",  # isort
    "B",  # bugbear
    # "UP",  # pyupgrade
    "N",  # pep8-naming
    "C90",  # bandit (security)
    "S"
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
  "fastapi.Depends","fastapi.params.Depends",
  # "fastapi.Query","fastapi.params.Query",
  # "fastapi.Body","fastapi.params.Body",
  # "fastapi.Header","fastapi.params.Header",
  # "fastapi.Path","fastapi.params.Path",
  # "fastapi.Cookie","fastapi.params.Cookie",
  # "fastapi.File","fastapi.params.File",
  # "fastapi.Form","fastapi.params.Form",
  # "fastapi.Security","fastapi.params.Security",
]
